//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HOMENEEDSEntities1 : DbContext
    {
        public HOMENEEDSEntities1()
            : base("name=HOMENEEDSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<tblAdmin> tblAdmins { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblCustomer> tblCustomers { get; set; }
        public virtual DbSet<tblLocation> tblLocations { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
    
        public virtual int uspRegisterUser(string email_Address, string password)
        {
            var email_AddressParameter = email_Address != null ?
                new ObjectParameter("Email_Address", email_Address) :
                new ObjectParameter("Email_Address", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspRegisterUser", email_AddressParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> uspCheckUserAlreadyRegistered(string email_Address, string mobile_number)
        {
            var email_AddressParameter = email_Address != null ?
                new ObjectParameter("Email_Address", email_Address) :
                new ObjectParameter("Email_Address", typeof(string));
    
            var mobile_numberParameter = mobile_number != null ?
                new ObjectParameter("mobile_number", mobile_number) :
                new ObjectParameter("mobile_number", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("uspCheckUserAlreadyRegistered", email_AddressParameter, mobile_numberParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> uspLogin(string email_Address, string mobile_number, string password)
        {
            var email_AddressParameter = email_Address != null ?
                new ObjectParameter("Email_Address", email_Address) :
                new ObjectParameter("Email_Address", typeof(string));
    
            var mobile_numberParameter = mobile_number != null ?
                new ObjectParameter("mobile_number", mobile_number) :
                new ObjectParameter("mobile_number", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("uspLogin", email_AddressParameter, mobile_numberParameter, passwordParameter);
        }
    }
}
