//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCart
    {
        public int Item_No { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
